### ISSUE TITLE
SaveSession assumes everything is dconf/gsettings based

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#111]
SaveSession uses merge_settings for the entire tree while we may have arbitrary data there, we probably want a static/class method (independent of instance) in each collector that does merging of two changesets and then we call that method per pair per settings domain (gsettings, libreoffice, nm, goa...)

**Comment by olivergs** [comment]
Already implemented method for merging settings based on collector, and not overall in commit 81b39d3d3fe0450716e4748ceb72554e29b3c768
