### ISSUE TITLE
rename systemd service unit as fleet-commander-admin instead of -dbus

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#133]
the -dbus suffix doesn't really mean anything

**Comment by olivergs** [comment]
Ok. The reason it was called -dbus was because we had another unit called fleet-commander-admin for the fleet commander standalone version on early ages.

**Comment by olivergs** [comment]
Fixed on commit 32a50b2bb3a9f0e083c1884570cf6d394667cd87
