### ISSUE TITLE
/var/lib/fleet-commander-admin directory is necessary for building

### ISSUE THREAD

**Issue by sk3r** [fleet-commander/fc-admin#139]
it's supposed to be created when installing the rpm package, but rpmbuild will fail if the directory doesn't exist.

**Comment by aruiz** [comment]
I can indeed reproduce. This is the aftermath of adding the custom install target. The easiest fix is just to not install the directory in the Makefile and document this in the README when building from tarballs.

**Comment by olivergs** [comment]
Removed the install-data-local target until fixed
`install-data-local:
 	install -d ${adminstatedir}
 	install -d ${profilesdir}`
