### ISSUE TITLE
when ssh connection is not present we get a cryptic error

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#150]
When the ssh connection for libvirt is not available the error shown to the user is "Could not access fingerprint" which does not help to assess the problem.

**Comment by olivergs** [comment]
Will check it. There are some changes in the SSH module in the FreeIPA integration branch, so I will check it as soon as I merge it into master.

**Comment by olivergs** [comment]
This is fixed in the FreeIPA branch and will be merged into master as soon as tests are fixed and the whole integration can be reviewed
