### ISSUE TITLE
Generalize the client and use oVirt to run VMs

### ISSUE THREAD

**Issue by mykaul** [fleet-commander/fc-admin#153]
Fleet Commander can both use oVirt to run its VM (and not libvirt) and provision on oVirt the desktop VMs.

I've looked at the libvirt code, and it seems trivial (I'm not sure why libvirt Python binding is not used, but that's a different issue), but since it's not an interface, it may be a bit more challenging to do. Apart from it, it should be fairly easy to implement.

(An alternative is to look at Apache's libcloud to generalize the interface. This regretfully does not have yet an oVirt driver though...)

**Comment by aruiz** [comment]
I'm not sure I'm for the idea of trying to talk anything else other than libvirt. Setting up a host with libvirt is rather trivial and works in most distros, oVirt and others are rather complicated to run.

What would be the benefit of the added code complexity of supporting more solutions given the ubiquity of libvirt?

**Comment by mykaul** [comment]
The end goal would be the use case of deploying desktop on oVirt. If you plan to deploy in masses in oVirt, just do the first one in oVirt as well.

**Comment by aruiz** [comment]
I appreciate the suggestion, but Fleet Commander is not a VDI solution, we use desktop VMs to run a simple 1 or 2 "template" images that resemble that of the deployed images on people's workstations.

I'm afraid we have to refuse this proposal.
