### ISSUE TITLE
RFE: Display the GSettings in a more readable way during the Review and Submit part

### ISSUE THREAD

**Issue by fidencio** [fleet-commander/fc-admin#163]
I'm not sure whether this bug should be here, in the logger part or in both parts.

It would help a lot people who're not familiar with GSettings' names to filter out whatever were the changes made.

**Comment by aruiz** [comment]
When you say GSettings names what do you mean? The path?

**Comment by fidencio** [comment]
For instance, instead of showing /org/gnome/desktop/background/picture-uri 'file:///user/share/....' what not show something like:
GNOME Background: <preview of the picture> (or even keeping the patch to the file as a first approach).

**Comment by aruiz** [comment]
I'm not sure we can scale going through every single config key and giving them human readable names... paths for settings are common practice across frameworks (Chrome, Firefox, LibreOffice) and sysadmins deal with pretty horrible paths in the Windows registry, this is already way nicer and I'm not sure that we can do much better.

**Comment by fidencio** [comment]
Fair enough! :-)

I'm closing the RFE, thanks for the explanation, @aruiz.
