### ISSUE TITLE
RFE: Firefox settings support

### ISSUE THREAD

**Issue by olivergs** [fleet-commander/fc-admin#168]
### Settings support

Firefox settings are located in a file named prefs.js located in a firefox profile directory.
Firefox profiles are located under

`$HOME/.mozilla/firefox/`

and they are named using 8 alphanumeric chararcters a dot and the profile name, so the preferences path could be something like this:

`$HOME/.mozilla/firefox/fhdy7she.default/prefs.js`

To get the default profile we need to open the file profiles.ini file and find the profile that has Default=1. 
This file is located at:

`$HOME/.mozilla/firefox/profiles.ini`

And an example of the contents of this file:

```
[General]
StartWithLastProfile=0

[Profile0]
Name=default
IsRelative=1
Path=robuvvg2.default
Default=1

[Profile1]
Name=Clean
IsRelative=1
Path=bd8ay27s.Clean
```
### Preferences format

The prefs.js file contains calls to a function called user_pref that sets each preference for this profile. For example:

```
user_pref("browser.download.panel.shown", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
```

We can create JSON lists data removing the function syntax and generating a settings object containing each setting pair:

```
var settings = {
    "browser.download.panel.shown": true,
    "accessibility.typeaheadfind.flashBar": 0,
    ...
}
```
The deployment for this data is specified in https://github.com/fleet-commander/fc-client/issues/9

**Comment by aruiz** [comment]
Have a look at this so that we can also support locked preferences in Firefox as well at some point:
http://kb.mozillazine.org/Locking_preferences (basically instead of pref() we use lockPref())

**Comment by olivergs** [comment]
ok. Will add it to the scoping :+1:

**Comment by olivergs** [comment]
Feature added in PR #177
