### ISSUE TITLE
Do not use 'virtio' as video type in libvirtcontroller.py

### ISSUE THREAD

**Issue by fidencio** [fleet-commander/fc-admin#193]
In https://github.com/fleet-commander/fc-admin/blob/master/admin/fleetcommander/libvirtcontroller.py#L228 fc-admin tries to create a video device which has as type 'virtio'. Although it works properly on recent Fedora and RHEL, this is not present in CentOS7.

Using 'qxl' as a video type would be a safer option.

**Comment by aruiz** [comment]
I remember we ran into issues on this due to the javascript SPICE client and the SPICE team recommended we switched it. I'd be happy to switch back if we verify everything works properly.

**Comment by fidencio** [comment]
@aruiz, I'd be happy to consider this patch here as something that could be taken as a "downstream patch" to be applied to the EPEL repo.

'virtio' type works well on Fedora and RHEL because those support virtio device drivers, which doesn't happen with CentOS. Unfortunately, the package is distributed through the same channel to RHEL and CentOS. :-/

I'd basically give it a try with latest RHEL and I've already tested with latest CentOS. If everything works well, I'd just have it applied to the package but not pushed to the project's git.

**Comment by olivergs** [comment]
Closed by commit fc9f26ee60886102ef29c23038e20d1a80e353a6
