### ISSUE TITLE
Do not let users connect to running VMs for LiveSession

### ISSUE THREAD

**Issue by fidencio** [fleet-commander/fc-admin#196]
We should not start already running VMs for LiveSession. Although I'm pretty sure it's agreed between FleetCommander developers as the running VMs are grayed out, just graying the VM out but leaving it exposed and there to be selected is not a good user experience (mainly when you have only one VM making it hard to know that "grayed out" VMs are not the expected ones).

I'd suggest to either try to make the running VMs not able to be selected or just do not show them at all as the user should **not** connect to them in any case for the LiveSession.

**Comment by olivergs** [comment]
Closed in PR #202
