### ISSUE TITLE
Add virsh command requirement for libvirt machine into documentation

### ISSUE THREAD

**Issue by olivergs** [fleet-commander/fc-admin#201]

**Comment by aruiz** [comment]
Can you elaborate on this? I don't think the requirement is clear and why is it a requirement

**Comment by olivergs** [comment]
In our libvirtmanager module we use the virsh command to get libvirt connection details:

https://github.com/fleet-commander/fc-admin/blob/master/admin/fleetcommander/libvirtcontroller.py#L103-L106

That command is not installed by default in centos even having a functional libvirt environment because virsh is in a separate package called libvirt-client. Have to check in F29, RHEL, etc, but makes sense to not have that package installed if you are using that machine to remotely run VMs

**Comment by aruiz** [comment]
Why do we use virsh? Isn't this something we can do using the libvirt API?

**Comment by olivergs** [comment]
This is done as a previous step to connect to libvirt machine, and it is done because for session mode, we need the socket file we are connecting to in the remote machine. The only way we have the socket present is to have libvirtd executed in session mode, so for that we issue a virsh list command, that at the same time allows us to know livbirt is working if the command exits with 0 error code.

If there is another way to achieve this previously to connect to libvirt, I do not know it, but I can have a look for a better way at some point.

**Comment by aruiz** [comment]
check if the socket file is present, if it's not, execute "libvirt -d" as the user, that should do it
