### ISSUE TITLE
Improve Profile Changes UI

### ISSUE THREAD

**Issue by stanislavlevin** [fleet-commander/fc-admin#218]
If I have a lot of changes I want to save then it's too tediously to click on each of them.
![screenshot_20190227_124530](https://user-images.githubusercontent.com/31205609/53482999-8eaecc80-3a91-11e9-80fe-4258db83d8de.png)

**Comment by olivergs** [comment]
Thank you Stanislav!

The UI rework is in our roadmap, but your PR is a good improvement we can add on this release.

I will check it during this week and add it to master branch.
