### ISSUE TITLE
Improve logger protocol

### ISSUE THREAD

**Issue by stanislavlevin** [fleet-commander/fc-admin#240]
For now, the logger protocol relies on the fact that the data being sent by logger from the qemu guest will be successfully received by the admin end. There aren't any attributes of the mature protocol such as header, control sum, etc., but plain JSON.

For example, the buffer limitations make sense. Actually, there are many buffer layers, each of them could break the FC protocol. For example, on my test machine, FC silently fails to transfer over 32768 bytes. These limitations depend on hardware, OS, etc.

**Comment by olivergs** [comment]
Currently, FC leaves the protocol handling to SPICE. Usually the information chunks are less than 1KB, no more than 32KB, so we never had the cache problem.

Now with your implementation the protocol details only relies in your code, so I understand you need this control over the data chunks being sent.

Anyway this is an enhancement that would include to main codebase so we can assure that problem could not appear in the future. I've not checked the code yet, but I could suppose it should work both for spice and external viewer modes?

**Comment by stanislavlevin** [comment]
What seemed impossible is now a reality (BIG data, big chunks, :smile:  ).

> I've not checked the code yet, but I could suppose it should work both for spice and external viewer modes?

Exactly.
