### ISSUE TITLE
SPICE-html5 client stops without any apparent error

### ISSUE THREAD

**Issue by olivergs** [fleet-commander/fc-admin#242]
The spice-html5 client freezes suddenly without any specific error thrown.
After some checks it seems that the screen is still receiving and sending input and window locations but canvas stopped to update the display rendering.

Need further debugging to detect the real cause.

**Comment by stanislavlevin** [comment]
Same here.

**Comment by olivergs** [comment]
Added a workaround with a reconnection button so if the client is frozen you can force a reconnection without losing live session changes. Added on commit de96fbb078d104ed8343bcf236eab3adb4e0217f

I will leave the issue open to try to find the real reason of the problem, but seems more complicated that it looks at a first glance.

**Comment by olivergs** [comment]
Fixed in #247
