### ISSUE TITLE
Allow to connect via ssh to non-standard port

### ISSUE THREAD

**Issue by r3pek** [fleet-commander/fc-admin#243]
I have SSH on a non-standard port. The "Fleet Commander virtual environment host" field doesn't "understand" the logic of [ip]:[port]

**Comment by stanislavlevin** [comment]
Hi, @r3pek. Thank you for the report. Indeed, this doesn't work even for '22'.
Please, see the mentioned PR.

**Comment by r3pek** [comment]
@stanislavlevin thx for fixing it this fast ;)
is there any way i can force the configuration while a new release isn't published?

**Comment by stanislavlevin** [comment]
The only way is the applying of that patch by manual. It's very easy.
`/usr/share/fleet-commander-admin/python/fleetcommander/fcdbus.py`:
```diff
    def parse_hypervisor_hostname(self, hostname):
-       hostdata = hostname.split()
+       hostdata = hostname.split(':', maxsplit=1)
        if len(hostdata) == 2:
```
Note: don't forget to restart FC dbus session.

**Comment by r3pek** [comment]
Don't think this change is enough....
This is what I get in the server console:
fleet-commander-admin[328297]: ERROR:root:Error getting hypervisor fingerprint: Error getting host keys: b'getaddrinfo <host>:<port>: Name or service not known\r\ngetaddrinfo <host>:<port>: Name or service not known\r\ngetaddrinfo <host>:<port>: Name or service not known\r\n'

(I restarted cockpit after making the change)

**Comment by stanislavlevin** [comment]
Cockpit killing is not enough, for example:
```
systemctl stop cockpit.socket
systemctl stop cockpit
ps -aux | grep -F fleetcommander.fcdbus
```
I've verified the PR on my side.

**Comment by stanislavlevin** [comment]
FC self kills on idle timeout (IIRC 60sec)

**Comment by olivergs** [comment]
Yes. FC has a self killing timer. Usually 60s unless you are connected to a live session.

**Comment by r3pek** [comment]
I've killed the fleetcommander.fcbus process, but still get the same error (getaddrinfo failed)
