### ISSUE TITLE
Possible problems when running template machines with refression on QEMU

### ISSUE THREAD

**Issue by olivergs** [fleet-commander/fc-admin#249]
Upstream bug: https://bugs.launchpad.net/qemu/+bug/1860759

We need to check if this affect us and how to workaround this

**Comment by mrandybu** [comment]
At this point after accepting the changes in the logger and closing template it does not revert to its original state. This is because the qemu `snapshot` option does not work because it conflicts with the `blockdev` option. To return the working state it is necessary disable conflicting option.

**Comment by olivergs** [comment]
Thanks for the contribution.

Checked the error on F32 and yes, without this fix changes are saved to template machine.

The fix works marvels, but the tests now are broken.

Are you willing to check them?

**Comment by olivergs** [comment]
Fixed by #257
