### ISSUE TITLE
FC-logger is not currently tracking firefox settings

### ISSUE THREAD

**Issue by mrandybu** [fleet-commander/fc-admin#255]
The fc-logger is not currently tracking firefox settings. The problem is as follows:
firefox has a file `~/.mozilla/firefox/profiles.ini`, which stores meta information about profiles, including the path to the profile. FC-logger reads `profiles.ini` and looks for a profile with the `Default = 1` option, from where it takes the path to the profile. But `Default = 1` option does not guarantee that this profile will be used when firefox starts. Accordingly, hence the problem that fc-logger is looking for a profile with firefox settings in the wrong path.

In the same directory (`~/.mozilla/firefox/`) there is another file `installs.ini`, which contains information about the current profile that firefox is currently using. I think installs.ini should be used.

**Comment by olivergs** [comment]
Fixed in PR #256
