### ISSUE TITLE
ScreenSaverInhibitor can't inhibit mate-screensaver

### ISSUE THREAD

**Issue by ptrNine** [fleet-commander/fc-admin#264]
Commit https://github.com/fleet-commander/fc-admin/commit/1328efb74b8cbe0d017d4451fd4a6d585deb7a46 introduced the list of known screensavers, but it does not have `org.mate.ScreenSaver`.

**Comment by olivergs** [comment]
Thank you very much. I will add it ASAP

Cheers!
