### ISSUE TITLE
[webui] missing fc-logger

### ISSUE THREAD

**Issue by stanislavlevin** [fleet-commander/fc-admin#282]
If `fc-logger` is not installed on VM template then the behaviour of `fc-admin` may confuse users.

During VM session a user makes some changes, see `Review and submit` button available/enabled and after clicking on that button wonders that there are no changes actually made.

This is typical error of setup.

**Comment by olivergs** [comment]
You're right. It is documented that the logger needs to be installed in the template VM, but we do not handle any warning for the user.

We could just set a message by default in the review and submit dialog, telling the user comething like:

"There are no changes reported by FC logger. Either you did not make any changes in configuration or FC logger is not installed in the template VM."

That way the user gets a hint about what is happening.

Other option would be to wait for an initial message from logger and after a timeout show a dialog about logger not being present.

Both options have the shortcoming that the user could have been doing changes before getting notified that logger is not present.

Do you have any other idea for this?

**Comment by olivergs** [comment]
Ok. I've just seen the PR. I will take a look to it. Thanks!
