### ISSUE TITLE
group 'users' does not exist

### ISSUE THREAD

**Issue by rothgar** [fleet-commander/fc-admin#5]
Using RHEL 7.2 during install of fleet-commander-admin I get the following error

```
useradd: group 'users' does not exist
error: %pre(fleet-commander-admin-0.2.0-1.el7.centos.noarch) scriptlet failed, exit status 6
Error in PREIN scriptlet in rpm package fleet-commander-admin-0.2.0-1.el7.centos.noarch
```

I assume this is because we are using LDAP for user logins and obviously do not have the local users group. There should be a better way to detect this so installation doesn't fail.

**Comment by aruiz** [comment]
Good catch! I need to give it some thought as to how to solve this properly.

**Comment by olivergs** [comment]
All ok. Tested and build correctly. Go ahead

**Comment by aruiz** [comment]
This bug is obsolete as of Fedora 24, I ned to update instructions to try this with RHEL/CentOS 7

**Comment by olivergs** [comment]
This is obsolete because now Fleet Commander Admin does not require any special group to be executed.
