### ISSUE TITLE
Disable turned on machine/domains from the list of templates

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#58]
If an already running VM is selected as template kernel errors are shown while it runs as the qcow image is blocked.

We should disable these machines from the list of templates (perhaps still list them but with some annotation claiming that they are unavailable as they are running).

**Comment by olivergs** [comment]
Would do add a (running) and disable the link. This would do for both requirements (not being able to use it and inform the user about why)

**Comment by olivergs** [comment]
Fixed in PR #89
