### ISSUE TITLE
GOA accounts are stored in a list instead of an object

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#87]
GOA accounts are stored in a list on each profile such as:
[{"Account 1": {...}},
{"Account 2": {...}}]

However parsing this adds an extra layer (the array) that is quite unnecessary, this data is basically the equivalent of using an object:
{"Account 1": {...},
 "Account 2: {...}}

Is there a reason for this that I'm missing?

**Comment by olivergs** [comment]
Fixed in PR #88
