### ISSUE TITLE
cleanup applies and index

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#90]
as of now we don't check whether applies.json contains references to non existing profiles uids

I suggest we should cleanup applies.json from invalid uids on the following events:
- service startup
- profile addition
- profile removal

**Comment by olivergs** [comment]
In fact, we should "standarize" and do cleanup of all writing/reading processes involving index, applies or profiles, so we can assure no malformed data is saved/read.

**Comment by aruiz** [comment]
Sounds good
