### ISSUE TITLE
Spice slow and cursor not shown during GDM login

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#92]

**Comment by olivergs** [comment]
Ok. I've tested the patch sent by Cristophe Fergau and installed kernel image 4.8.0-0.rc2.git3.1.f25.

I've installed it in F24 and in a fresh rawhide image.
In F24: The cursor does not show at all
In Rawhide, Cursor shows, but not responding to clicks or the clicks got misplaced like if they had an offset.
Anyway, in Rawhide I'm having problems with spice-html5 but with spice with boxes and virtmanager also.

**Comment by olivergs** [comment]
Due to the comment from Pavel Grunt here: https://bugs.freedesktop.org/show_bug.cgi?id=94776
I've tested the virtio driver and it works very good to fix this.

I've proposed a branch for testing in PR #131

**Comment by olivergs** [comment]
Merged PR #131
