### ISSUE TITLE
GOA: Display should match the GNOME Online Accounts settings UI display name

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#96]
For example, "Windows Live" should be displayed as "Microsoft Account".

**Comment by olivergs** [comment]
This could be done if we add another information field to GOA providers file. Currently we only have this:

`[Provider windows_live]
MailEnabled=true
DocumentsEnabled=true`

We need to talk with GOA maintainer to request adding this kind of information to supported providers introspection tool so we can generate it with the display name included.

**Comment by aruiz** [comment]
sounds like a plan
